# Generated by Django 3.2.22 on 2023-10-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0020_auto_20231024_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='filter_text_include',
            field=models.BooleanField(default=True, help_text='On to include filter text, off to exclude filter text', verbose_name='Toggle include/exclude'),
        ),
    ]
